# Generated by Django 5.1.7 on 2025-05-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_rename_baner_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_main',
            field=models.ImageField(upload_to='img/banner'),
        ),
    ]
