# Generated by Django 5.1.7 on 2025-05-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_user_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_user',
            field=models.CharField(max_length=20),
        ),
    ]
