# Generated by Django 5.1.7 on 2025-05-17 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_user_card_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banerfon',
            new_name='BannerFon',
        ),
    ]
