# Generated by Django 5.1.7 on 2025-05-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_alter_banner_name_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_main',
            field=models.ImageField(upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='speed',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_banner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url_banner',
            field=models.URLField(blank=True, null=True),
        ),
    ]
