# Generated by Django 5.1.7 on 2025-05-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_alter_banner_image_main_alter_banner_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerfon',
            name='image_back',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
