# Generated by Django 5.1.7 on 2025-05-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_alter_film_type_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='language',
            field=models.CharField(choices=[('uk', 'Украинский'), ('ru', 'Русский')], default='uk', max_length=2),
        ),
    ]
