# Generated by Django 5.1.7 on 2025-05-31 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_film_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='date_publication',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='about',
            name='publication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='film',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='name_uk',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
