# Generated by Django 5.1.7 on 2025-06-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_about_date_publication_about_publication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_about_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_about_uk',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
