# Generated by Django 5.1.7 on 2025-06-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_about_description_ru_about_description_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
