# Generated by Django 5.1.7 on 2025-06-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0015_about_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='date_publication',
            field=models.DateField(),
        ),
    ]
