# Generated by Django 5.1.7 on 2025-06-04 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0016_alter_about_date_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
