# Generated by Django 5.1.7 on 2025-06-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0017_alter_about_date_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='baner',
            new_name='banner',
        ),
        migrations.AddField(
            model_name='hall',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='name_hall_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='name_hall_uk',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
