# Generated by Django 5.1.7 on 2025-06-10 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0021_cinema_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='hall',
        ),
        migrations.AddField(
            model_name='hall',
            name='cinema',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema'),
            preserve_default=False,
        ),
    ]
