# Generated by Django 5.1.7 on 2025-06-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0024_hall_date_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_template', models.CharField()),
                ('path_template', models.FileField(upload_to='sample/', verbose_name='Загрузить HTML-письмо ')),
            ],
        ),
    ]
