# Generated by Django 5.1.7 on 2025-07-06 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0025_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='gall',
        ),
        migrations.RemoveField(
            model_name='session',
            name='seo',
        ),
        migrations.AddField(
            model_name='session',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.hall'),
        ),
        migrations.AddField(
            model_name='session',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.price'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_session',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_session',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
