# Generated by Django 5.1.7 on 2025-07-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0027_session_type_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='booking',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('free', 'Свободно'), ('booked', 'Забронировано'), ('bought', 'Куплено')], default='free', max_length=10),
        ),
    ]
