# Generated by Django 5.1.7 on 2025-07-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0030_alter_cinema_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='adress',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='coord',
            field=models.URLField(max_length=300),
        ),
    ]
