# Generated by Django 5.1.7 on 2025-07-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0031_alter_cinema_adress_alter_cinema_coord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='coord',
            field=models.URLField(max_length=450),
        ),
    ]
