# Generated by Django 5.1.7 on 2025-05-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Baner',
            new_name='Banner',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='text_baner',
            new_name='text_banner',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='url_baner',
            new_name='url_banner',
        ),
    ]
