# Generated by Django 5.1.7 on 2025-05-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_banner_image_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='speed',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
