# Generated by Django 5.1.7 on 2025-05-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_rename_banerfon_bannerfon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='name_page',
            field=models.CharField(choices=[('Главная', 'Главная'), ('Акция', 'Акция')], max_length=100),
        ),
    ]
