# Generated by Django 5.1.7 on 2025-06-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0018_rename_baner_hall_banner_hall_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='col',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='hall',
            name='row',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
