# Generated by Django 5.1.7 on 2025-06-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0019_alter_hall_col_alter_hall_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='conditions',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='cinema',
            name='conditions_ru',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='conditions_uk',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='name_cinema_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='name_cinema_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='seo_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='seo_text_uk',
            field=models.TextField(null=True),
        ),
    ]
