# Generated by Django 5.1.7 on 2025-06-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0020_cinema_conditions_cinema_conditions_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='banner',
            field=models.ImageField(default='  ', upload_to='photos/'),
            preserve_default=False,
        ),
    ]
