# Generated by Django 5.1.7 on 2025-06-11 08:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0023_cinema_gall_cinema_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
