# Generated by Django 5.1.7 on 2025-07-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0026_remove_session_gall_remove_session_seo_session_hall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='type_film',
            field=models.CharField(default='2D', max_length=200),
            preserve_default=False,
        ),
    ]
